### ISSUE TITLE
Can't load `externals.agenda`

### ISSUE THREAD

**Issue by DarkKronicle** [juniorsundar/neorg_extras#19] opened 2024-08-22 16:26 UTC
Thanks for your awesome work on this plugin! I've been trying to update to the most recent version where the setup is handled by neorg, but I'm having an issue getting it to work.

On startup I get this error: 

```
'neorg.modules.externals.many-mans.module' not found:
no field package.preload['neorg.modules.externals.many-mans.module']
cache_loader: module neorg.modules.externals.many-mans.module not found
cache_loader_lib: module neorg.modules.externals.many-mans.module not found
```

I do have a bit of a weird setup using [nixCats](https://github.com/BirdeeHub/nixCats-nvim), but I haven't had any issues adding new plugins yet. Here's my [config](https://github.com/DarkKronicle/nvim-dotfiles/blob/rewrite/lua/modules/writing/plugins.lua#L4) (slightly outdated since I didn't want to push a broken version), but I've just followed the readme with
```
load = {
...
          ["externals.agenda"] = {},
        ["externals.roam"] = {},
        ["externals.many-mans"] = {},
}
```

Do you have any debugging tips? How neorg load the initial module, maybe I need to do something manually?

**Comment by juniorsundar** [comment] 2024-08-22 16:31
Have you included the repo in the dependencies for Neorg?
You have to do that so that the module gets downloaded and added to your runtime path.

```lua
return {
    "nvim-neorg/neorg",
    dependencies = {
        --vvvvvv This right here vvvvvv--
        "juniorsundar/neorg-extras",
        "nvim-telescope/telescope.nvim", -- Required for the Neorg-Roam features
        "nvim-lua/plenary.nvim" -- Required as part of Telescope installation
    },
    config = function()
        require('neorg').setup({
            load = {
                ["externals.agenda"] = {},
                ["externals.roam"] = {},
                -- And if you're a 50-cent fan
                ["externals.many-mans"] = {},
            })

        -- I add this line here because I want to open 
        -- up the default Neorg workspace whenever a Neovim instance
        -- is started
        require("neorg.core").modules.get_module("core.dirman").set_workspace("default") 
    end
}
```

**Comment by juniorsundar** [comment] 2024-08-22 16:31
I had a look at your configs. The issue is that its an underscore instead of a dash.

https://github.com/DarkKronicle/nvim-dotfiles/blob/c839927fcea269f1c237a4398889dd8c6ab17bf1/lua/modules/writing/plugins.lua#L12

More specifically: `"juniorsundar/neorg-extras"` instead of `"juniorsundar/neorg_extras"`

**Comment by DarkKronicle** [comment] 2024-08-22 18:14
I've pushed my current version, but it's still not working. 

I'll try to look into my runtime path.

**Comment by DarkKronicle** [comment] 2024-08-22 18:24
`vim.opt.runtimepaths` does have the `neorg-extras` repository. Doing `:lua require("neorg.modules.external.agenda")`, gives
```
require("neorg.modules.external.agenda") E5108: Error executing lua [string ":lua"]:1: module 'neorg.modules.external.agenda' not found:
	no field package.preload['neorg.modules.external.agenda']
cache_loader: module neorg.modules.external.agenda not found
cache_loader_lib: module neorg.modules.external.agenda not found
```

**Comment by juniorsundar** [comment] 2024-08-22 19:40
This error is expected because this isn't how you import the neorg modules.

I repeated your command on my end. I am also getting the same error as you are when running `:lua require("neorg.modules.external.agenda")`.

Can you try the following?
```
:lua require("neorg.core").modules.get_module("external.agenda").day_view()
```

or even

```
Neorg agenda page hold undone pending
```

BTW if you are trying to load the modules from neorg then the way to go about it is [as follows](https://github.com/nvim-neorg/neorg/blob/85f15f033d8c56366ac1e6ae93c940db8ad067ca/lua/neorg/core/modules.lua#L542-L553):

```lua
require("neorg.core").modules.get_module(<module>)
```

**Comment by DarkKronicle** [comment] 2024-08-23 00:17
Figured it out! I think it's a typo in the README, it should be `external`, not `externals`. Found it by looking at the [load_module](https://github.com/nvim-neorg/neorg/blob/85f15f033d8c56366ac1e6ae93c940db8ad067ca/lua/neorg/core/modules.lua#L483) code.

Thanks for the help! I'll leave this open if you want to close this when you fix the README, or feel free to close.

**Comment by juniorsundar-tii** [comment] 2024-08-23 05:27
I've [corrected the typo](https://github.com/juniorsundar/neorg-extras/commit/7a824767349d706764ce98cdc5db7cf2c43a7a4a) in the README.md. Hence closing this issue.

Thank you for finding this issue!

**Closed as completed by juniorsundar-tii** 2024-08-23 05:27 UTC
Labels: documentation
